// Generated by tools/generate.py; edit the definition there.
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Sensitivity {
    Public,
    Private,
    Sensitive,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PreferenceStatus {
    Observed,
    Approved,
    Corrected,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ProvenanceSource {
    User,
    Model,
    Native,
    Peer,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum HostKind {
    Android,
    Desktop,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Default)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DelegationLevel {
    #[default]
    ReadAndSuggest,
    PrepareDrafts,
    ActWithinScope,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Default)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum NetworkPolicy {
    #[default]
    OfflineOnly,
    ExistingProvider,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TaskTransition {
    Planned,
    WaitingForAccess,
    Drafted,
    ReadyForReview,
    InProgress,
    AwaitingVerification,
    Verified,
    Blocked,
    Cancelled,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ReceiptOutcome {
    Verified,
    ActionVerified,
    Responded,
    Unverified,
    NeedsUser,
    Failed,
    Cancelled,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ModelSelectionRule {
    LocalQualifiedOnly,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ApprovalState {
    Pending,
    Approved,
    Rejected,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ChangeKind {
    Upsert,
    Tombstone,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ProviderKind {
    Local,
    Gmail,
    Outlook,
    Imap,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DataKind {
    Account,
    Folder,
    Calendar,
    File,
    App,
    Record,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Operation {
    Read,
    Suggest,
    Draft,
    Organize,
    Send,
    Create,
    Update,
    Delete,
    Invite,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DispatchIntent {
    None,
    OpenComposer,
    OpenEventForm,
    ProviderRead,
    ProviderMutation,
    LocalMutation,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RecordKind {
    Persona,
    PersonalAgent,
    TaskSpec,
    TaskEvent,
    AgentSpec,
    TaskReceipt,
    Handoff,
    ReplicaChange,
    MailAccount,
    MessageRef,
    Draft,
    CalendarRef,
    EventRef,
    CapabilityGrant,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Version {
    pub major: u64,
    pub minor: u64,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Provenance {
    pub source: ProvenanceSource,
    pub actor_id: String,
    pub replica_id: String,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub evidence_ref: Option<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Preference {
    pub key: String,
    pub value: String,
    pub status: PreferenceStatus,
    pub provenance: Provenance,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Budget {
    pub max_steps: u64,
    pub max_tool_calls: u64,
    pub max_duration_ms: u64,
    pub max_bytes: u64,
    pub max_network_calls: u64,
    pub max_depth: u64,
    pub max_children: u64,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct DataScope {
    pub kind: DataKind,
    pub resource_id: String,
    pub operations: Vec<Operation>,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Scopes {
    pub capabilities: Vec<String>,
    pub tools: Vec<String>,
    pub data: Vec<DataScope>,
    pub recipients: Vec<String>,
    pub hosts: Vec<String>,
    pub operations: Vec<Operation>,
    #[serde(default)]
    pub delegation: DelegationLevel,
    #[serde(default)]
    pub network: NetworkPolicy,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Persona {
    pub person_id: String,
    pub revision: u64,
    pub preferences: Vec<Preference>,
    pub sensitivity: Sensitivity,
    pub provenance: Provenance,
    pub deleted: bool,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub corrects_revision: Option<u64>,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PersonalAgent {
    pub agent_id: String,
    pub person_id: String,
    pub profile_revision: u64,
    pub display_name: String,
    pub persona_revision: u64,
    pub conversation_refs: Vec<String>,
    pub capability_preferences: Vec<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct TaskSpec {
    pub task_id: String,
    pub agent_id: String,
    pub person_id: String,
    pub idempotency_key: String,
    pub goal: String,
    pub origin_replica_id: String,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub target_replica_id: Option<String>,
    pub host_requirements: Vec<HostKind>,
    pub scopes: Scopes,
    pub budget: Budget,
    pub created_at_ms: u64,
    pub deadline_ms: u64,
    pub expected_postcondition: String,
    pub user_visible_policy: String,
    pub sensitivity: Sensitivity,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct TaskEvent {
    pub event_id: String,
    pub operation_id: String,
    pub task_id: String,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub predecessor_event_id: Option<String>,
    pub origin_replica_id: String,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub assigned_replica_id: Option<String>,
    pub step: u64,
    pub deadline_ms: u64,
    pub transition: TaskTransition,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub evidence_ref: Option<String>,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub external_object_id: Option<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct AgentSpec {
    pub child_id: String,
    pub parent_task_id: String,
    pub purpose: String,
    pub template_version: u64,
    pub model_selection: ModelSelectionRule,
    pub scopes: Scopes,
    pub budget: Budget,
    pub depth: u64,
    pub expires_at_ms: u64,
    pub stop_generation: u64,
    pub verifier_id: String,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct TaskReceipt {
    pub operation_id: String,
    pub task_id: String,
    pub attempt_id: String,
    pub actor_id: String,
    pub replica_id: String,
    pub before_evidence_refs: Vec<String>,
    pub after_evidence_refs: Vec<String>,
    pub dispatch_intent: DispatchIntent,
    pub observed_effect: String,
    pub outcome: ReceiptOutcome,
    pub reason: String,
    pub source: ProvenanceSource,
    pub timestamp_ms: u64,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub external_object_id: Option<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Handoff {
    pub handoff_id: String,
    pub task_id: String,
    pub from_replica_id: String,
    pub target_replica_id: String,
    pub encrypted_goal: String,
    pub receipt_operation_ids: Vec<String>,
    pub host_requirements: Vec<HostKind>,
    pub approval: ApprovalState,
    pub expires_at_ms: u64,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct ReplicaChange {
    pub person_id: String,
    pub replica_id: String,
    pub sequence: u64,
    pub operation_id: String,
    pub record_id: String,
    pub record_kind: RecordKind,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub predecessor_operation_id: Option<String>,
    pub record_revision: u64,
    pub change: ChangeKind,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub ciphertext: Option<String>,
    pub content_hash: String,
    pub provenance: Provenance,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct MailAccount {
    pub account_id: String,
    pub person_id: String,
    pub provider: ProviderKind,
    pub display_name: String,
    pub address: String,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct MessageRef {
    pub account_id: String,
    pub message_id: String,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub thread_id: Option<String>,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub folder_id: Option<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct Draft {
    pub draft_id: String,
    pub task_id: String,
    pub account_id: String,
    #[serde(deserialize_with = "crate::required_nullable")]
    pub reply_to: Option<MessageRef>,
    pub recipients: Vec<String>,
    pub subject: String,
    pub body: String,
    pub attachment_refs: Vec<String>,
    pub revision: u64,
    pub approval: ApprovalState,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct CalendarRef {
    pub account_id: String,
    pub calendar_id: String,
    pub display_name: String,
    pub time_zone: String,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct EventRef {
    pub calendar: CalendarRef,
    pub event_id: String,
    pub start_ms: u64,
    pub end_ms: u64,
    pub time_zone: String,
    pub attendees: Vec<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct CapabilityGrant {
    pub grant_id: String,
    pub person_id: String,
    pub replica_id: String,
    pub scopes: Scopes,
    pub budget: Budget,
    pub issued_at_ms: u64,
    pub expires_at_ms: u64,
    pub stop_generation: u64,
    pub revoked: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(
    tag = "kind",
    content = "payload",
    rename_all = "SCREAMING_SNAKE_CASE",
    deny_unknown_fields
)]
pub enum Record {
    Persona(Persona),
    PersonalAgent(PersonalAgent),
    TaskSpec(TaskSpec),
    TaskEvent(TaskEvent),
    AgentSpec(AgentSpec),
    TaskReceipt(TaskReceipt),
    Handoff(Handoff),
    ReplicaChange(ReplicaChange),
    MailAccount(MailAccount),
    MessageRef(MessageRef),
    Draft(Draft),
    CalendarRef(CalendarRef),
    EventRef(EventRef),
    CapabilityGrant(CapabilityGrant),
}
