// Mounted real component; official mocked Tauri IPC. NOT native socket/OS evidence.
import assert from 'node:assert/strict';
import test from 'node:test';
import { createRequire } from 'node:module';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const frontend=fileURLToPath(new URL('../',import.meta.url)); const require=createRequire(join(frontend,'package.json'));
const tools=createRequire(join(resolve(process.env.PERSONAL_TEST_TOOL_ROOT||'/agent/workspace/test-tools'),'package.json'));
const {JSDOM}=tools('jsdom'); const React=require('react'); const {act}=React; const {mockIPC,clearMocks}=require('@tauri-apps/api/mocks');
const dir=mkdtempSync(join(tmpdir(),'peer-ui-')); process.on('exit',()=>rmSync(dir,{recursive:true,force:true})); const out=join(dir,'peer.cjs');
await require('esbuild').build({entryPoints:[join(frontend,'src/components/PeerSyncPanel.tsx')],outfile:out,bundle:true,platform:'node',format:'cjs',jsx:'automatic',plugins:[{name:'react',setup(b){b.onResolve({filter:/^react(?:\/.*)?$/},({path})=>({path:require.resolve(path),external:true}));}}]});
const {PeerSyncPanel}=require(out);
const offer={version:1,replica_id:'replica-a',person_id:'person-a',agent_id:'agent-a',fingerprint:'a'.repeat(64)};
const status=()=>({offer,peer:null,revoked:false,received:0,sent_ack:0,pending:1,message:'PEER_REVIEW_ONLY',tasks:[],persona_review:null});
async function mount(t, handler=()=>status()) {
 const dom=new JSDOM('<div id="root"></div>',{url:'https://peer.invalid/',pretendToBeVisual:true});
 const keys=['window','document','navigator','Event','MouseEvent','HTMLElement','IS_REACT_ACT_ENVIRONMENT'];const old=new Map(keys.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
 for(const k of keys)Object.defineProperty(globalThis,k,{configurable:true,writable:true,value:k==='IS_REACT_ACT_ENVIRONMENT'?true:dom.window[k]});
 const calls=[];mockIPC((command,args)=>{calls.push({command,args});if(command==='peer_sync_cancel')return null;if(command==='personal_agent_view')return {tasks:[]};if(command==='peer_sync_command')return handler(args.command);throw Error('Unexpected IPC '+command);});
 const root=require('react-dom/client').createRoot(document.getElementById('root'));const flush=async()=>{for(let i=0;i<3;i++)await act(async()=>{await new Promise(r=>setImmediate(r));});};
 t.after(async()=>{await act(async()=>root.unmount());await flush();clearMocks();dom.window.close();for(const[k,v]of old){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}});
 await act(async()=>root.render(React.createElement(PeerSyncPanel)));await flush();const c=document.getElementById('root');
 return {calls,c,dom,flush,text:()=>c.textContent,click:async text=>{const b=[...c.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(b,text);assert.equal(b.disabled,false);await act(async()=>b.dispatchEvent(new dom.window.MouseEvent('click',{bubbles:true})));await flush();},fill:async(label,value)=>{const e=c.querySelector(`[aria-label="${label}"]`);const proto=e.tagName==='TEXTAREA'?dom.window.HTMLTextAreaElement.prototype:e.tagName==='SELECT'?dom.window.HTMLSelectElement.prototype:dom.window.HTMLInputElement.prototype;await act(async()=>{Object.getOwnPropertyDescriptor(proto,'value').set.call(e,value);e.dispatchEvent(new dom.window.Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}));});await flush();},check:async()=>{await act(async()=>c.querySelector('input[type="checkbox"]').click());await flush();}};
}
test('no automatic pairing/network command on mount; honest opt-in and OS limits',async t=>{const h=await mount(t);assert.equal(h.calls.length,0);assert.match(h.text(),/Wi-Fi Direct.*not verified/);assert.match(h.text(),/does not merge/);assert.equal(window.localStorage.length,0);});
test('full fingerprint and explicit local approval with fixed selection required',async t=>{let captured;const h=await mount(t,c=>{captured=c;return status();});await h.click('Show my pairing identity');assert.match(h.text(),/a{64}/);let button=[...h.c.querySelectorAll('button')].find(b=>b.textContent==='Approve fingerprint and selected records');assert.ok(button.disabled);await h.fill('Peer offer',JSON.stringify({...offer,replica_id:'replica-b',fingerprint:'b'.repeat(64)}));await h.check();await h.fill('Identity choice','KEEP_SEPARATE_REVIEW');await h.click('Approve fingerprint and selected records');assert.equal(captured.action,'approve');assert.equal(captured.compared_fingerprint,true);assert.equal(captured.choice,'KEEP_SEPARATE_REVIEW');assert.deepEqual(captured.selection,{persona:false,task_ids:[]});});
test('identity mismatch surfaces native conflict without rewriting or sending',async t=>{const h=await mount(t,c=>{if(c.action==='approve')throw 'IDENTITY_CONFLICT: independent identities; nothing overwritten';return status();});await h.click('Show my pairing identity');await h.fill('Peer offer',JSON.stringify({...offer,person_id:'another-person'}));await h.check();await h.click('Approve fingerprint and selected records');assert.match(h.text(),/IDENTITY_CONFLICT/);assert.ok(!h.calls.some(c=>['listen','sync'].includes(c.args?.command?.action)));});
test('revocation confirmation and inert received tombstone stay visible',async t=>{let current={...status(),peer:{...offer,fingerprint:'b'.repeat(64)},received:2,tasks:[{task_id:'t',deleted:true,status:'DELETED',events:[]}]};const h=await mount(t,c=>{if(c.action==='revoke')current={...current,revoked:true};return current;});await h.click('Show my pairing identity');assert.match(h.text(),/Deleted task/);window.confirm=()=>false;await h.click('Revoke peer');assert.equal(h.calls.filter(c=>c.args?.command?.action==='revoke').length,0);window.confirm=()=>true;await h.click('Revoke peer');assert.match(h.text(),/REVOKED/);assert.match(h.text(),/cannot be remotely erased/);});
test('screen hidden cancels sockets and discards late sensitive result',async t=>{let resolveRequest;const h=await mount(t,()=>new Promise(r=>{resolveRequest=r;}));const button=[...h.c.querySelectorAll('button')][0];await act(async()=>button.click());Object.defineProperty(document,'hidden',{configurable:true,value:true});await act(async()=>document.dispatchEvent(new Event('visibilitychange')));Object.defineProperty(document,'hidden',{configurable:true,value:false});await act(async()=>resolveRequest(status()));await h.flush();assert.ok(h.calls.some(c=>c.command==='peer_sync_cancel'));assert.doesNotMatch(h.text(),/a{64}/);});

test('unified adoption requires separate archive consent and explicit future shared-task selection',async t=>{
 let captured;const h=await mount(t,c=>{captured=c;return status();});await h.click('Show my pairing identity');await h.fill('Peer offer',JSON.stringify({...offer,replica_id:'replica-b',fingerprint:'b'.repeat(64)}));await h.check();await h.fill('Identity choice','UNIFY_ARCHIVE');
 const button=[...h.c.querySelectorAll('button')].find(b=>b.textContent==='Approve fingerprint and selected records');assert.ok(button.disabled);assert.match(h.text(),/ALL current local persona\/tasks.*immutable local archive/);
 for(const fragment of ['I explicitly approve archiving','Share all new shared tasks']) { const label=[...h.c.querySelectorAll('label')].find(l=>l.textContent.includes(fragment));await act(async()=>label.querySelector('input').click());await h.flush(); }
 await h.click('Approve fingerprint and selected records');assert.equal(captured.choice,'UNIFY_ARCHIVE');assert.equal(captured.compared_fingerprint,true);assert.deepEqual(captured.selection.task_ids,['00000000-0000-0000-0000-000000000000']);assert.ok(!h.calls.some(c=>['listen','sync'].includes(c.args?.command?.action)));
});
