import { useState, useEffect, useCallback } from 'react';
import { tauriApi, type DesktopCapabilityProfile, type FeatureStatus } from '../lib/tauri';

const statusLabel: Record<FeatureStatus, string> = {
  VERIFIED_WORKING: 'Verified Working',
  BUILDS_NOT_RUNTIME_TESTED: 'Builds, Not Runtime Tested',
  IMPLEMENTED_NOT_TESTED: 'Implemented, Not Tested',
  PARTIALLY_IMPLEMENTED: 'Partially Implemented',
  NOT_IMPLEMENTED: 'Not Implemented',
  BLOCKED_BY_ENVIRONMENT: 'Blocked by Environment',
  FAILED: 'Failed',
};

const statusColor: Record<FeatureStatus, { bg: string; text: string }> = {
  VERIFIED_WORKING: { bg: 'rgba(34,197,94,0.12)', text: 'var(--success)' },
  BUILDS_NOT_RUNTIME_TESTED: { bg: 'rgba(59,130,246,0.12)', text: '#60a5fa' },
  IMPLEMENTED_NOT_TESTED: { bg: 'rgba(234,179,8,0.12)', text: '#facc15' },
  PARTIALLY_IMPLEMENTED: { bg: 'rgba(245,158,11,0.12)', text: '#fbbf24' },
  NOT_IMPLEMENTED: { bg: 'rgba(107,114,128,0.12)', text: '#9ca3af' },
  BLOCKED_BY_ENVIRONMENT: { bg: 'rgba(239,68,68,0.12)', text: '#f87171' },
  FAILED: { bg: 'rgba(239,68,68,0.2)', text: '#ef4444' },
};

const features: Array<{ key: keyof DesktopCapabilityProfile; label: string }> = [
  { key: 'vault', label: 'USB Vault' },
  { key: 'recording', label: 'Real Audio Recording' },
  { key: 'browser', label: 'Browser Workspace' },
  { key: 'vision', label: 'Vision / OCR / Camera' },
  { key: 'voice', label: 'Offline STT / TTS' },
  { key: 'model', label: 'Local Model Inference' },
  { key: 'agent', label: 'Agent Loop' },
  { key: 'documents', label: 'Documents & Memory' },
  { key: 'security', label: 'Security & Manifest' },
  { key: 'hardware', label: 'Hardware Profile' },
  { key: 'accessibility', label: 'Accessibility' },
  { key: 'usb', label: 'USB Asset Alignment' },
];

export function CapabilityProfile() {
  const [profile, setProfile] = useState<DesktopCapabilityProfile | null>(null);
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const loadProfile = useCallback(async () => {
    setIsLoading(true);
    setError('');
    try {
      const result = await tauriApi.getDesktopCapabilityProfile();
      setProfile(result);
    } catch (err) {
      setError(`Failed to load capability profile: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadProfile();
  }, [loadProfile]);

  return (
    <div>
      <div className="main-header">
        <h2>Capability Profile</h2>
        <div className="main-header-actions">
          <button className="btn btn-secondary btn-sm" onClick={loadProfile} disabled={isLoading}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="1 4 1 10 7 10" />
              <path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10" />
            </svg>
            {isLoading ? 'Refreshing…' : 'Refresh'}
          </button>
        </div>
      </div>

      <div className="main-body">
        <div className="settings-view">
          <div className="settings-section">
            <div className="settings-section-header">📊 Truthful Desktop Capability Status</div>
            <div className="settings-section-body">
              <p style={{ fontSize: '13px', color: 'var(--text-secondary)', marginBottom: '16px' }}>
                This profile is generated by the Rust backend at runtime. It reports only the
                P1-approved status vocabulary and reflects the actual state of binaries, models,
                USB detection, and code readiness on this host.
              </p>

              {error && (
                <div
                  style={{
                    marginBottom: '16px',
                    padding: '12px',
                    background: 'var(--error-bg)',
                    color: 'var(--error-text)',
                    borderRadius: 'var(--radius-sm)',
                    fontSize: '13px',
                  }}
                >
                  {error}
                </div>
              )}

              {!profile && !error && (
                <div style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>Loading capability profile…</div>
              )}

              {profile && (
                <div
                  style={{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
                    gap: '12px',
                  }}
                >
                  {features.map(feature => {
                    const status = profile[feature.key] as FeatureStatus;
                    const colors = statusColor[status];
                    return (
                      <div
                        key={feature.key}
                        style={{
                          padding: '12px',
                          borderRadius: 'var(--radius-md)',
                          border: '1px solid var(--border)',
                          background: 'var(--bg-primary)',
                        }}
                      >
                        <div style={{ fontSize: '13px', color: 'var(--text-secondary)', marginBottom: '6px' }}>
                          {feature.label}
                        </div>
                        <div
                          style={{
                            display: 'inline-block',
                            padding: '4px 10px',
                            borderRadius: '999px',
                            fontSize: '12px',
                            fontWeight: 600,
                            background: colors.bg,
                            color: colors.text,
                          }}
                        >
                          {statusLabel[status]}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}

              {profile && profile.notes.length > 0 && (
                <div style={{ marginTop: '20px' }}>
                  <div style={{ fontSize: '14px', fontWeight: 600, marginBottom: '10px' }}>Notes</div>
                  <ul style={{ paddingLeft: '20px', fontSize: '13px', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                    {profile.notes.map((note, idx) => (
                      <li key={idx}>{note}</li>
                    ))}
                  </ul>
                </div>
              )}

              {profile && (
                <div style={{ marginTop: '16px', fontSize: '12px', color: 'var(--text-muted)' }}>
                  Generated at {profile.generated_at_utc}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
