// Generated by packages/personal-agent-contracts/tools/generate.py.
package com.unoone.agent.core.personal

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

sealed interface PersonalRecord
@Serializable
enum class Sensitivity { PUBLIC, PRIVATE, SENSITIVE }
@Serializable
enum class PreferenceStatus { OBSERVED, APPROVED, CORRECTED }
@Serializable
enum class ProvenanceSource { USER, MODEL, NATIVE, PEER }
@Serializable
enum class HostKind { ANDROID, DESKTOP }
@Serializable
enum class DelegationLevel { READ_AND_SUGGEST, PREPARE_DRAFTS, ACT_WITHIN_SCOPE }
@Serializable
enum class NetworkPolicy { OFFLINE_ONLY, EXISTING_PROVIDER }
@Serializable
enum class TaskTransition { PLANNED, WAITING_FOR_ACCESS, DRAFTED, READY_FOR_REVIEW, IN_PROGRESS, AWAITING_VERIFICATION, VERIFIED, BLOCKED, CANCELLED }
@Serializable
enum class ReceiptOutcome { VERIFIED, ACTION_VERIFIED, RESPONDED, UNVERIFIED, NEEDS_USER, FAILED, CANCELLED }
@Serializable
enum class ModelSelectionRule { LOCAL_QUALIFIED_ONLY }
@Serializable
enum class ApprovalState { PENDING, APPROVED, REJECTED }
@Serializable
enum class ChangeKind { UPSERT, TOMBSTONE }
@Serializable
enum class ProviderKind { LOCAL, GMAIL, OUTLOOK, IMAP }
@Serializable
enum class DataKind { ACCOUNT, FOLDER, CALENDAR, FILE, APP, RECORD }
@Serializable
enum class Operation { READ, SUGGEST, DRAFT, ORGANIZE, SEND, CREATE, UPDATE, DELETE, INVITE }
@Serializable
enum class DispatchIntent { NONE, OPEN_COMPOSER, OPEN_EVENT_FORM, PROVIDER_READ, PROVIDER_MUTATION, LOCAL_MUTATION }
@Serializable
enum class RecordKind { PERSONA, PERSONAL_AGENT, TASK_SPEC, TASK_EVENT, AGENT_SPEC, TASK_RECEIPT, HANDOFF, REPLICA_CHANGE, MAIL_ACCOUNT, MESSAGE_REF, DRAFT, CALENDAR_REF, EVENT_REF, CAPABILITY_GRANT }

@Serializable
data class Version(
    val major: Long,
    val minor: Long,
)

@Serializable
data class Provenance(
    val source: ProvenanceSource,
    val actor_id: String,
    val replica_id: String,
    val evidence_ref: String?,
)

@Serializable
data class Preference(
    val key: String,
    val value: String,
    val status: PreferenceStatus,
    val provenance: Provenance,
)

@Serializable
data class Budget(
    val max_steps: Long,
    val max_tool_calls: Long,
    val max_duration_ms: Long,
    val max_bytes: Long,
    val max_network_calls: Long,
    val max_depth: Long,
    val max_children: Long,
)

@Serializable
data class DataScope(
    val kind: DataKind,
    val resource_id: String,
    val operations: List<Operation>,
)

@Serializable
data class Scopes(
    val capabilities: List<String>,
    val tools: List<String>,
    val data: List<DataScope>,
    val recipients: List<String>,
    val hosts: List<String>,
    val operations: List<Operation>,
    val delegation: DelegationLevel = DelegationLevel.READ_AND_SUGGEST,
    val network: NetworkPolicy = NetworkPolicy.OFFLINE_ONLY,
)

@Serializable
data class Persona(
    val person_id: String,
    val revision: Long,
    val preferences: List<Preference>,
    val sensitivity: Sensitivity,
    val provenance: Provenance,
    val deleted: Boolean,
    val corrects_revision: Long?,
) : PersonalRecord

@Serializable
data class PersonalAgent(
    val agent_id: String,
    val person_id: String,
    val profile_revision: Long,
    val display_name: String,
    val persona_revision: Long,
    val conversation_refs: List<String>,
    val capability_preferences: List<String>,
) : PersonalRecord

@Serializable
data class TaskSpec(
    val task_id: String,
    val agent_id: String,
    val person_id: String,
    val idempotency_key: String,
    val goal: String,
    val origin_replica_id: String,
    val target_replica_id: String?,
    val host_requirements: List<HostKind>,
    val scopes: Scopes,
    val budget: Budget,
    val created_at_ms: Long,
    val deadline_ms: Long,
    val expected_postcondition: String,
    val user_visible_policy: String,
    val sensitivity: Sensitivity,
) : PersonalRecord

@Serializable
data class TaskEvent(
    val event_id: String,
    val operation_id: String,
    val task_id: String,
    val predecessor_event_id: String?,
    val origin_replica_id: String,
    val assigned_replica_id: String?,
    val step: Long,
    val deadline_ms: Long,
    val transition: TaskTransition,
    val evidence_ref: String?,
    val external_object_id: String?,
) : PersonalRecord

@Serializable
data class AgentSpec(
    val child_id: String,
    val parent_task_id: String,
    val purpose: String,
    val template_version: Long,
    val model_selection: ModelSelectionRule,
    val scopes: Scopes,
    val budget: Budget,
    val depth: Long,
    val expires_at_ms: Long,
    val stop_generation: Long,
    val verifier_id: String,
) : PersonalRecord

@Serializable
data class TaskReceipt(
    val operation_id: String,
    val task_id: String,
    val attempt_id: String,
    val actor_id: String,
    val replica_id: String,
    val before_evidence_refs: List<String>,
    val after_evidence_refs: List<String>,
    val dispatch_intent: DispatchIntent,
    val observed_effect: String,
    val outcome: ReceiptOutcome,
    val reason: String,
    val source: ProvenanceSource,
    val timestamp_ms: Long,
    val external_object_id: String?,
) : PersonalRecord

@Serializable
data class Handoff(
    val handoff_id: String,
    val task_id: String,
    val from_replica_id: String,
    val target_replica_id: String,
    val encrypted_goal: String,
    val receipt_operation_ids: List<String>,
    val host_requirements: List<HostKind>,
    val approval: ApprovalState,
    val expires_at_ms: Long,
) : PersonalRecord

@Serializable
data class ReplicaChange(
    val person_id: String,
    val replica_id: String,
    val sequence: Long,
    val operation_id: String,
    val record_id: String,
    val record_kind: RecordKind,
    val predecessor_operation_id: String?,
    val record_revision: Long,
    val change: ChangeKind,
    val ciphertext: String?,
    val content_hash: String,
    val provenance: Provenance,
) : PersonalRecord

@Serializable
data class MailAccount(
    val account_id: String,
    val person_id: String,
    val provider: ProviderKind,
    val display_name: String,
    val address: String,
) : PersonalRecord

@Serializable
data class MessageRef(
    val account_id: String,
    val message_id: String,
    val thread_id: String?,
    val folder_id: String?,
) : PersonalRecord

@Serializable
data class Draft(
    val draft_id: String,
    val task_id: String,
    val account_id: String,
    val reply_to: MessageRef?,
    val recipients: List<String>,
    val subject: String,
    val body: String,
    val attachment_refs: List<String>,
    val revision: Long,
    val approval: ApprovalState,
) : PersonalRecord

@Serializable
data class CalendarRef(
    val account_id: String,
    val calendar_id: String,
    val display_name: String,
    val time_zone: String,
) : PersonalRecord

@Serializable
data class EventRef(
    val calendar: CalendarRef,
    val event_id: String,
    val start_ms: Long,
    val end_ms: Long,
    val time_zone: String,
    val attendees: List<String>,
) : PersonalRecord

@Serializable
data class CapabilityGrant(
    val grant_id: String,
    val person_id: String,
    val replica_id: String,
    val scopes: Scopes,
    val budget: Budget,
    val issued_at_ms: Long,
    val expires_at_ms: Long,
    val stop_generation: Long,
    val revoked: Boolean,
) : PersonalRecord
